#!/usr/bin/env python

# Copyright 2020 Boston Dynamics Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DEBUG_IMAGE = False
if DEBUG_IMAGE:
    import cv2

import numpy as np
import threading

import rospy
from sensor_msgs.msg import Image
from geometry_msgs.msg import PolygonStamped
from std_msgs.msg import Float32MultiArray, Float32, Bool
from cv_bridge import CvBridge

THERMAL_REF_TOPIC = 'thermal_reference_temp'
IMAGE_TOPIC = 'temperature_image'
FRAME_MSMT_RAW_TOPIC_SUFFIX = '_raw_frame_msmt'
FRAME_MSMT_TOPIC_SUFFIX = '_frame_msmt'
FULL_TOPIC = 'full_skin_temp'
REPEAT_TOPIC = 'repeated_skin_temp'
FULL_DATA_TOPIC = 'full_data_skin_temp'
REPEAT_DATA_TOPIC = 'repeated_data_skin_temp'
REGION_TOPIC = 'skin_temp_roi'
TRACKING_STATUS_TOPIC = 'ir_tracking_status'
HELPER_TIMER_PERIOD_SEC = 1
REPEAT_MSMT_PERIOD_SEC = 5
FULL_MSMT_PERIOD_SEC = 10
NOMINAL_RATE_HZ = 27
NOMINAL_MIN_SAMPLES = REPEAT_MSMT_PERIOD_SEC * NOMINAL_RATE_HZ
NOMINAL_FULL_SAMPLES = FULL_MSMT_PERIOD_SEC * NOMINAL_RATE_HZ
OK_FRAC_MSMT = 0.7
MAX_DROPOUT_BEFORE_RESET_SEC = 0.5

MIN_REF_TEMP = 30.0
MAX_REF_TEMP = 40.0

ROS_THERMAL_IMAGE_BUFFER_SIZE = 640*480 * 2 * 3

class SkinTemperature(object):
    def thermal_ref_callback(self, data):
        if data.data < MIN_REF_TEMP or data.data > MAX_REF_TEMP:
            rospy.logwarn_throttle(1, '{}: Thermal ref temp out of valid range:'.format(
                self.name, data.data))
            return

        with self.lock:
            self.thermal_ref_temp = data.data

    def image_callback(self, data):
        t = data.header.stamp.to_sec()

        with self.lock:
            if self.tlast is None:
                self.tlast = t
                return

            # Detect backward jumps in time in replay.
            if self.tlast > t:
                self.clear_msmt_state()
                self.tlast = t
                rospy.logwarn_throttle(1, '{}: Backward jump in time'.format(self.name))
                return

            # Detect skips in data.
            if t - self.tlast > MAX_DROPOUT_BEFORE_RESET_SEC:
                rospy.logwarn_throttle(1, '{}: Dropped samples for {} sec'.format(
                    self.name, t - self.tlast))
                self.clear_msmt_state()
                self.tlast = t
                return

            if self.delta is None:
                self.delta = t - self.tlast
                return

            self.delta = self.delta_alpha * (t - self.tlast) + (1 - self.delta_alpha) * self.delta
            self.tlast = t

            if self.use_thermal_ref:
                if self.thermal_ref_temp is None:
                    rospy.logwarn_throttle(1, '{}: No thermal ref temp received.'.format(self.name))
                    return

                tr_xmin = self.thermal_ref_prm['xmin']
                tr_ymin = self.thermal_ref_prm['ymin']
                tr_xmax = self.thermal_ref_prm['xmax']
                tr_ymax = self.thermal_ref_prm['ymax']
            else:
                tr_xmin = None; tr_ymin = None; tr_xmax = None; tr_ymax = None

            if not self.roiset:
                rospy.logwarn_throttle(1, '{}: No ROI received.'.format(self.name))
                return

            xmin = self.xmin
            ymin = self.ymin
            xmax = self.xmax
            ymax = self.ymax
        # End locked region.

        cv_image = self.bridge.imgmsg_to_cv2(data, desired_encoding='passthrough')
        (rows, cols) = cv_image.shape

        if self.use_thermal_ref and (tr_xmin < 0 or tr_ymin < 0 or tr_xmax >= cols or tr_ymax >= rows):
            with self.lock:
                rospy.logwarn_throttle(1, '{}: Bad thermal ref roi {} image size {}- disabling.'.format(
                    self.name, self.thermal_ref_prm, (rows, cols)))
                self.use_thermal_ref = False
                return

        if xmin < 0 or ymin < 0 or xmax >= cols or ymax >= rows:
            with self.lock:
                rospy.logwarn_throttle(1, '{}: edge of frame at {}, seq {}. {} {} {} {} {} {}'.format(
                    self.name, t, data.header.seq, xmin, xmax, cols, ymin, ymax, rows))
                self.clear_msmt_state()
                return

        if DEBUG_IMAGE:
            imin = np.amin(cv_image)
            imax = np.amax(cv_image)
            irange = imax - imin
            if irange != 0:
                cv_image_dbg = cv2.convertScaleAbs((cv_image - imin) * 255 / irange)
                cv2.rectangle(cv_image_dbg, (xmin, ymin), (xmax, ymax), (0,0,0), 2)
                if self.use_thermal_ref:
                    cv2.rectangle(cv_image_dbg, (tr_xmin, tr_ymin), (tr_xmax, tr_ymax), (0,0,0), 2)
                cv2.imshow('temperature ROI', cv_image_dbg)
                cv2.waitKey(1)

                cv2.imshow('zoomed temperature ROI', cv_image[ymin:ymax, xmin:xmax])
                cv2.waitKey(1)

                if self.use_thermal_ref:
                    cv2.imshow('zoomed reference ROI', cv_image[tr_ymin:tr_ymax, tr_xmin:tr_xmax])
                    cv2.waitKey(1)

        if cv_image[ymin:ymax, xmin:xmax].size == 0 or (self.use_thermal_ref and cv_image[tr_ymin:tr_ymax, tr_xmin:tr_xmax].size == 0):
            with self.lock:
                rospy.logwarn_throttle(1, '{}: empty image at {}, seq {}'.format(
                    self.name, t, data.header.seq))
                self.clear_msmt_state()
                return

        val = np.amax(cv_image[ymin:ymax, xmin:xmax])
        msg = Float32()

        msg.data = val
        self.debug_msmt_raw_pub.publish(msg)

        ref_val = None
        if self.use_thermal_ref:
            ref_val = np.mean(cv_image[tr_ymin:tr_ymax, tr_xmin:tr_xmax])
            val *= self.thermal_ref_temp / ref_val

        if np.isnan(val) or (self.use_thermal_ref and np.isnan(ref_val)):
            with self.lock:
                rospy.logwarn_throttle(1, '{}: NaN at {}, seq {}'.format(
                    self.name, t, data.header.seq))
                self.clear_msmt_state()
                return

        msg.data = val
        self.debug_msmt_pub.publish(msg)

        with self.lock:
            if (self.repeat_msmt_n >= self.repeat_msmt_buffer.size):
                self.repeat_msmt_buffer.resize((2 * self.repeat_msmt_buffer.size), refcheck=False)
            self.repeat_msmt_buffer[self.repeat_msmt_n] = val
            if self.repeat_msmt_n == 0: self.r_ti = t
            self.repeat_msmt_n += 1
            self.r_tf = t

            if (self.full_msmt_n >= self.full_msmt_buffer.size):
                self.full_msmt_buffer.resize((2 * self.full_msmt_buffer.size), refcheck=False)
            self.full_msmt_buffer[self.full_msmt_n] = val
            if self.full_msmt_n == 0: self.f_ti = t
            self.full_msmt_n += 1
            self.f_tf = t
        # End locked region.

    def region_callback(self, data):
        if len(data.polygon.points) != 2:
            return

        with self.lock:
            self.xmin = int(data.polygon.points[0].x)
            self.ymin = int(data.polygon.points[0].y)
            self.xmax = int(data.polygon.points[1].x)
            self.ymax = int(data.polygon.points[1].y)
            if (self.xmax - self.xmin) <= 0 or (self.ymax - self.ymin) <= 0:
                return

            self.roiset = True

    def tracking_status_callback(self, data):
        with self.lock:
            if not self.roi_valid or not data.data:
                # Clear the measurement buffer unless we are valid, staying valid.
                self.clear_msmt_state()
            self.roi_valid = data.data

    def msmt_helper_callback(self, event):
        with self.lock:
            if not self.roi_valid or not self.roiset:
                rospy.logwarn_throttle(1, '{}: No valid ROI received.'.format(self.name))
                self.clear_msmt_state()
                return

            delta = self.delta

            r_ti = self.r_ti
            r_tf = self.r_tf
            r_msmt_n = self.repeat_msmt_n
            r_data = np.copy(self.repeat_msmt_buffer[0:self.repeat_msmt_n])
            r_do_it = r_ti is not None and r_tf is not None and r_tf - r_ti >= REPEAT_MSMT_PERIOD_SEC
            if r_do_it:
                self.repeat_msmt_n = 0
            f_ti = self.f_ti
            f_tf = self.f_tf
            f_msmt_n = self.full_msmt_n
            f_data = np.copy(self.full_msmt_buffer[0:self.full_msmt_n])
            f_do_it = f_ti is not None and f_tf is not None and f_tf - f_ti >= FULL_MSMT_PERIOD_SEC
            if f_do_it:
                self.full_msmt_n = 0
        # End locked region.

        if r_do_it:
            self.msmt_callback(event, r_ti, r_tf, r_msmt_n, r_data, delta, repeated=True)
        if f_do_it:
            self.msmt_callback(event, f_ti, f_tf, f_msmt_n, f_data, delta, repeated=False)

    def msmt_callback(self, event, ti, tf, msmt_n, data, delta, repeated=True):
        if repeated:
            txt = 'repeat'
            period = REPEAT_MSMT_PERIOD_SEC
            data_pub = self.repeat_data_pub
            msmt_pub = self.repeat_msmt_pub
        else:
            txt = 'full'
            period = FULL_MSMT_PERIOD_SEC
            data_pub = self.full_data_pub
            msmt_pub = self.full_msmt_pub

        if delta is None or delta < 1e-3 or msmt_n < OK_FRAC_MSMT * period / delta:
            rospy.loginfo_throttle(1, '{} {}: not enough samples {}'.format(self.name, txt, msmt_n))
            return

        msg = Float32MultiArray()
        msg.data = data
        data_pub.publish(msg)

        val = np.median(data)
        rospy.loginfo('{} {}: {:.1f} deg C; nsamp: {}; ti: {:.1f}; tf: {:.1f}; delta: {:.4f}'.format(
            self.name, txt, val, data.shape[0], ti, tf, (tf - ti) / data.shape[0]))

        msg = Float32()
        msg.data = val
        msmt_pub.publish(msg)

    def clear_msmt_state(self):
        rospy.logwarn_throttle(1, '{}: Resetting'.format(self.name))

        # Region of Interest
        self.roi_valid = False
        self.roiset = False
        self.xmin = 0
        self.xmax = 0
        self.ymin = 0
        self.ymax = 0

        self.r_ti = None
        self.r_tf = None
        self.repeat_msmt_n = 0
        self.f_ti = None
        self.f_tf = None
        self.full_msmt_n = 0

        self.tlast = None
        self.delta = None

    def __init__(self, name):
        self.name = name

        self.lock = threading.Lock()

        # Measurement buffers
        self.repeat_msmt_buffer = np.zeros(NOMINAL_MIN_SAMPLES)
        self.full_msmt_buffer = np.zeros(NOMINAL_FULL_SAMPLES)

        self.clear_msmt_state()

        # Software time delta calculation
        self.delta_alpha = 0.8

        self.bridge = CvBridge()

        self.debug_msmt_pub = rospy.Publisher(self.name + FRAME_MSMT_TOPIC_SUFFIX,
                                              Float32,
                                              queue_size=10)
        self.debug_msmt_raw_pub = rospy.Publisher(self.name + FRAME_MSMT_RAW_TOPIC_SUFFIX,
                                                  Float32,
                                                  queue_size=10)

        self.full_msmt_pub = rospy.Publisher(FULL_TOPIC, Float32, queue_size=10)
        self.repeat_msmt_pub = rospy.Publisher(REPEAT_TOPIC, Float32,
                                               queue_size=10)
        self.full_data_pub = rospy.Publisher(FULL_DATA_TOPIC, Float32MultiArray,
                                             queue_size=10)
        self.repeat_data_pub = rospy.Publisher(REPEAT_DATA_TOPIC,
                                               Float32MultiArray,
                                               queue_size=10)

        self.use_thermal_ref = rospy.get_param('use_thermal_reference', False)
        self.thermal_ref_prm = rospy.get_param('thermal_reference_prm', None)
        if self.use_thermal_ref:
            if self.thermal_ref_prm is None or not all([self.thermal_ref_prm.has_key(key) for key in ['xmin', 'ymin', 'xmax', 'ymax']]):
                self.use_thermal_ref = False
                rospy.logwarn('{}: Missing thermal reference parameters; {}'.format(
                    self.name, self.thermal_ref_prm))
            else:
                if (self.thermal_ref_prm['xmax'] - self.thermal_ref_prm['xmin']) <= 0 or (self.thermal_ref_prm['ymax'] - self.thermal_ref_prm['ymin']) <= 0:
                    self.use_thermal_ref = False
                    rospy.logwarn('{}: Bad thermal reference parameters; {}'.format(
                        self.name, self.thermal_ref_prm))
                else:
                    self.thermal_ref_sub = rospy.Subscriber(THERMAL_REF_TOPIC,
                                                            Float32,
                                                            self.thermal_ref_callback,
                                                            queue_size=1)
                    self.thermal_ref_temp = None

        self.image_sub = rospy.Subscriber(IMAGE_TOPIC, Image, self.image_callback,
                                          queue_size=1,
                                          buff_size=ROS_THERMAL_IMAGE_BUFFER_SIZE)
        self.region_sub = rospy.Subscriber(REGION_TOPIC, PolygonStamped,
                                           self.region_callback,
                                           queue_size=1)
        self.tracking_status_sub = rospy.Subscriber(TRACKING_STATUS_TOPIC, Bool,
                                                    self.tracking_status_callback,
                                                    queue_size=1)

        self.msmt_helper_timer = rospy.Timer(rospy.Duration(HELPER_TIMER_PERIOD_SEC),
                                             self.msmt_helper_callback)

if __name__ == '__main__':
    rospy.init_node('skin_temperature')
    temp = SkinTemperature(rospy.get_name())
    rospy.spin()
