#!/usr/bin/env python

# Copyright 2020 Boston Dynamics Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This requires the yoctopuce module (python -m pip install yoctopuce)

import sys

DEBUG_PLOT = False
if DEBUG_PLOT:
    import matplotlib.pyplot as plt

import numpy as np
import threading

import rospy
from std_msgs.msg import Float32

from yoctopuce.yocto_api import YAPI, YRefParam
from yoctopuce.yocto_temperature import YTemperature

TOPIC = 'thermal_reference_temp'

class ThermalReference(object):

    def __init__(self, name, target='any'):
        self.name = name
        rospy.loginfo('{} : Constructor called'.format(self.name))
        self.name = name
        self.temperature_pub = rospy.Publisher(TOPIC, Float32, queue_size=10)

        # Setup the API to use local USB devices
        errmsg = YRefParam()
        if YAPI.RegisterHub('usb', errmsg) != YAPI.SUCCESS:
            sys.exit('init error' + errmsg.value)
        if target == 'any':
            # retrieve any temperature sensor
            self.sensor = YTemperature.FirstTemperature()
            if self.sensor is None:
                sys.exit('No module connected (check USB connection)')
        else:
            self.sensor = YTemperature.FindTemperature(target + '.temperature')

        if not (self.sensor.isOnline()):
            sys.exit('Device not connected (check USB connection)')

    def measure_temperature(self):
        temp = self.sensor.get_currentValue()
        rospy.loginfo('{} Temp : {:2.1f} C'.format(self.name, temp))
        msg = Float32()
        msg.data = temp # thermal reference temp
        self.temperature_pub.publish(msg)
    
    def spin(self):
        while self.sensor.isOnline():
            self.measure_temperature()
            YAPI.Sleep(1000)

if __name__ == '__main__':
    rospy.init_node('thermal_reference_temperature')
    temp = ThermalReference(rospy.get_name())
    temp.spin()
