#!/usr/bin/env python

import sys

from drspot.rqt.vitals_readout import VitalsReadout
from rqt_gui.main import Main

plugin = 'rqt_vitals_readout'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))